//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVCService.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public class Animal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Age { get; set; }

        public Animal()
        {
            Id = 0;
            Name = "";
            Type = "";
            Age = 0;
        }

        public Animal(string name, string type, int age)
        {
            Id = 2;
            Name = name;
            Type = type;
            Age = age;
        }

        public override string ToString()
        {
            StringBuilder outputString = new StringBuilder("", 100);

            outputString.Append(Name);
            outputString.Append("<br>");
            outputString.Append(Type);
            outputString.Append("<br>");
            outputString.Append(Age);
            outputString.Append("<br>");

            return outputString.ToString();
        }
    }
}
